name: Run Checks

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Install cocoapod generate
        run: sudo gem install cocoapods-generate
      - name: Run Check
        run: ./gradlew check