# Adapted from https://github.com/code-with-the-italians/bundel/blob/main/.github/workflows/dependencies.yml
name: dependency updates

on:
  workflow_dispatch:
  schedule:
    # Every Friday at 4:32 (note scheduled jobs might be delayed or skipped)
    - cron: '32 4 * * 5'

jobs:
  check:
    name: Check for updated dependencies
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          ref: main
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: 11
          distribution: 'adopt'
      - name: Check for dependency updates
        run: ./gradlew versionCatalogUpdate --no-daemon
      - name: Setup Python
        uses: actions/setup-python@v2
      - name: Create PR message
        uses: jannekem/run-python-script-action@v1
        id: message
        with:
          script: |
            import json

            f = open('build/dependencyUpdates/report.json')
            data = json.load(f)

            message = "I found a new version for those dependencies!\n"

            for item in data['outdated']['dependencies']:
            	group = item['group']
            	newVersion = item['available']['milestone']
            	oldVersion = item['version']
            	name = item['name']
            	#-$group:$name [$oldVersion -> $newVersion]
            	newVersionMessage="- *{}:{}* [{} -> {}]".format(group, name, oldVersion, newVersion)
            	message += "\n{}".format(newVersionMessage)

            print(message)

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3
        with:
          commit-message: Dependency updates
          delete-branch: true
          branch: catalog-dependency-updates
          title: 🤖 Dependency updates
          body: ${{ steps.message.outputs.stdout }}
